### ISSUE TITLE
Crash when using 'Ice Barrage' on a Target Dummy from "MmmMmmMmmMmm" 

### ISSUE THREAD

**Issue by megatrook** [Etienne-mc/spells-lab-extra-spells-1.20.1#1]
Upon using this spell on a target dummy, my game crashes, just as the projectile hits the dummy it seems

**Comment by Etienne-mc** [comment]
What version of the Wizards mod were you using ?
Ice Barrage uses a projectile from Wizards, which name changed after the 1.1.0 release, and it is currently checking for the new one
If you're using a past version of Wizards, I'm guessing the old name doesn't match, so it likely causes that crash

Updating Wizards should fix it!

**Comment by megatrook** [comment]
oop, yep! that was the issue, thanks! it works fine now :D sorry for the false alarm!
