### ISSUE TITLE
STDERR When Firing Arrow Rain

### ISSUE THREAD

**Issue by InputandOutput** [Etienne-mc/spells-lab-extra-spells-1.20.1#2]
[log_snippet.txt](https://github.com/user-attachments/files/15914417/log_snippet.txt)
The log snippet shows an error after successfully firing Arrow Rain at a target. Though it doesn't affect gameplay negatively, it does contribute to considerable log spam, especially for an archer player that uses spells a lot.

**Comment by Etienne-mc** [comment]
Fixed with release 1.2-1.20.1
Thanks!
