### ISSUE TITLE
Rogue class problem [idea]

### ISSUE THREAD

**Issue by shoverno2** [Etienne-mc/spells-lab-extra-spells-1.20.1#4]
I've been playing rogue class for a while, and it has a flaw.
Very first skill for this class is "Slice and dice", skill that supposed to be used with fast attack weapons to stack up buff quickly.
However, such weapons has lacks attack range.
It's so short that player inevitably takes damage in close combat with melee mobs.
This class is fragile, and stun skill has long cooldown for consistent use,
+ stun doesn't works with bosses.
This all makes iconic weapon for this class, dual knifes, the worst

This class needs something to avoid damage in close quarters with melee mobs.
A brief evasion of all melee attacks could be an option.

Though, this sounds like better stun skill.

What about changing RMB skill to parry? (Slice and dice could go to second skill slot)

In cocept:
Channel skill for 2 seconds. After usage, 2 seconds or interruption skill goes on cooldown of 3 seconds with no effect.
Next incoming attack will activate skill and finish channel immediatly:
- incoming damage parried (ignored)
- attacker takes damage and stunned for 2 seconds
(damage should be applied only with rogue weapon)
- projectile bounces aside
(attacker isn't affected when using ranged attack)

Realisation could be:
Channel for 2 second, targetting single entity within range of 2,5.
Activation on hit:
- incoming damage instance ignored
- targeted entity stunned for 2 seconds
- targeted entity also takes offhand fast* weapon damage
- interrupt cast if channel cancelled or expired
Cooldown 3 seconds.

In the end, dual knifes becoming more relevant weapons set for rogue.
Overall, class becomes stronger in duel combat, as it should.

   * "fast" as sickle or faster; if not mistaken, attack speed value for sickle is 2

P.S.
It's different from second skill of "trickster" class that comes with "Arsenal and Classes" spell engine addon. Though, might be good example.

**Comment by Etienne-mc** [comment]
Hi!
Thank you for the detailed feedback, however I think you've mixed up mods here.
The Rogue class is added by the **Rogues & Warriors** mod by Daedelus - [Rogues & Warriors (RPG Series)](https://www.curseforge.com/minecraft/mc-mods/rogues-and-warriors)

**Spells Lab - Extras** only adds a fifth spell for each base class from the RPG Series.
Currently, there is no support for **Rogues & Warriors**, so none of the Rogues spells were added by this mod.
I suggest you send this feedback to the **Rogues & Warriors** github page, or directly on the RPG Series discord, in the suggestion channel.
